config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :accountings
  resources :tasks
  resources :categories
  resources :buildings
  resources :events
  resources :games
  resources :users
  resources :groups do
    resources :task_logs
    resources :constructed_buildings do
      resources :event_logs
    end
  end

  get '/add_event_log', to: 'event_logs#add'
  get '/add_task_log', to: 'task_logs#add'
  get '/start_task_log', to: 'task_logs#start'

  root to: 'groups#index'

end

app/models/task.rb
class Task < ApplicationRecord
  has_many :task_logs

  validates :name, :presence => true
  validates :value, :presence => true
  validates :duration_min, :presence => true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_admin
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @tasks = Task.all
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_url, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to tasks_url, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :location, :duration_min, :value, :comment, :settlement_immediately, :optional)
    end
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :task_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :task_description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :task_location %>
  </div>

  <div class="field">
    <%= form.label :duration_min %>
    <%= form.number_field :duration_min, id: :task_duration_min %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value, id: :task_cost %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :task_comment %>
  </div>

  <div class="field">
    <%= form.label :optional %>
    <%= form.check_box :optional, id: :task_optional %>
    <p>Der Betrag wird beim Spielende automatisch verbucht, wenn eine Aufgabe nicht als Optional markiert ist. Dies ist nur bei negativen Beträgen sinnvoll.</p>
  </div>

  <div class="field">
    <%= form.label :settlement_immediately %>
    <%= form.check_box :settlement_immediately, id: :task_settlement_immediately %>
    <p>Beim erledigen wird der Betrag unmittelbar verbucht.</p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_tasks.html.erb
<div class="row">
  <% @tasks.each do |task| %>
      <div class="col-4">
        <div class="card">
          <div class="card-header">
            <div class="float-right">
            <% if task.optional %>
              <span class="badge badge-success badge-pill float-right" title="<%= "#{Task.human_attribute_name(:optional)}" %>">
                <%= icon 'check' %>
                <%= "#{Task.human_attribute_name(:optional)}" %>
              </span>
            <% else %>
              <span class="badge badge-warning badge-pill float-right" title="<%= "#{Task.human_attribute_name(:optional)}" %>">
                <%= icon 'close' %>
                <%= "#{Task.human_attribute_name(:optional)}" %>
              </span>
            <% end %>
            <br/>
            <% if task.settlement_immediately %>
              <span class="badge badge-success badge-pill float-right" title="<%= "#{Task.human_attribute_name(:settlement_immediately)}" %>">
                <%= icon 'check' %>
                <%= "#{Task.human_attribute_name(:settlement_immediately)}" %>
              </span>
          <% else %>
              <span class="badge badge-warning badge-pill float-right" title="<%= "#{Task.human_attribute_name(:settlement_immediately)}" %>">
                <%= icon 'close' %>
                <%= "#{Task.human_attribute_name(:settlement_immediately)}" %>
              </span>
            <% end %>
            </div>
            <h4><%= task.name %></h4>
            <% if current_user.admin? %>
              <span class="float-right">
                <%= icon_link_to 'pencil', t(:edit), edit_task_path(task) %>
                <%= icon_link_to 'trash', t(:delete), task, method: :delete, data: { confirm: t(:are_you_sure?) } %>
              </span>
            <% end %>
            <div class="row">
              <div class="col-4">
                <%= icon 'dollar', title: "#{Event.human_attribute_name(:impact)}" %>
                <span class="number-format"><%= task.value %></span>
              </div>
              <div class="col-8">
                <%= icon 'clock-o', title: "#{Event.human_attribute_name(:duration)}" %>
                <%= "#{task.duration_min} #{t(:minutes)}" %>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-12"><%= task.description %></div>
            </div>
            <% unless @game.nil? %>
              <hr/>
              <form action="<%= add_task_log_path %>" method="get">
                <div class="form-group">
                  <select class="form-control form-control-sm" name="group">
                    <option value="all"><%= t(:all) %></option>
                    <% @game.groups.each do |group| %>
                        <option value="<%= group.id %>"><%= group.name %></option>
                    <% end %>
                  </select>
                </div>
                <input name="game" value="<%= @game.id %>" hidden>
                <input name="task" value="<%= task.id %>" hidden>
                <button type="submit" class="btn btn-primary btn-sm pull-right">
                  <%= t(:schedule_task) %>
                </button>
              </form>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<%= render layout: 'layouts/content_header', locals: {title: Task.model_name.human(count: 2)} do %>
  <%= icon_link_to 'plus', t(:new), new_task_path %>
<% end %>

<%= render 'tasks', partial: @tasks %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>