config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :accountings
  resources :tasks
  resources :categories
  resources :buildings
  resources :events
  resources :games
  resources :users
  resources :groups do
    resources :task_logs
    resources :constructed_buildings do
      resources :event_logs
    end
  end

  get '/add_event_log', to: 'event_logs#add'
  get '/add_task_log', to: 'task_logs#add'
  get '/start_task_log', to: 'task_logs#start'

  root to: 'groups#index'

end

app/models/event_log.rb
class EventLog < ApplicationRecord
  belongs_to :event
  belongs_to :constructed_building

  def end
    self.start.advance(minutes: self.event.duration_min)
  end

  def remaining_time
    remaining_time = (self.start.getutc + self.event.duration_min * 60) - DateTime.now.getutc
    remaining_time > 0 ? remaining_time : 0
  end

  def remaining_impact
    remaining_impact = self.event.impact_percent * (self.remaining_time / (self.event.duration_min * 60))
    remaining_impact > 0 ? remaining_impact : 0
  end
end

app/controllers/event_logs_controller.rb
class EventLogsController < ApplicationController
  before_action :set_vars, only: [:index, :show, :edit, :update]
  before_action :set_event_log, only: [:show, :edit, :update, :destroy]

  # GET /event_logs
  def index
    @event_logs = EventLog.all
  end

  # GET /event_logs/1
  def show
  end

  # GET /event_logs/new
  def new
    @event_log = EventLog.new
  end

  def add
    game = Game.find(params[:game])
    if params[:group] == 'all'
      game.groups.each do |group|
        create_event_log(params, group)
      end
    else
      group = Group.find(params[:group])
      create_event_log(params, group)
    end
    redirect_to game_path(params[:game])
  end

  # GET /event_logs/1/edit
  def edit
  end

  # POST /event_logs
  def create
    @event_log = EventLog.new(event_log_params)

    if @event_log.save
      redirect_to @event_log, notice: 'Event log was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /event_logs/1
  def update
    if @event_log.update(event_log_params)
      redirect_to @event_log, notice: 'Event log was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /event_logs/1
  def destroy
    @event_log.destroy
    redirect_to event_logs_url, notice: 'Event log was successfully destroyed.'
  end

  private
  def create_event_log(params, group)
    if params[:building] == 'all'
      group.constructed_buildings_finished.each do |constructed_building|
        event_log = EventLog.new(
            constructed_building: constructed_building,
            event_id: params[:event].to_i,
            start: DateTime.now)
        event_log.save!
      end
    else
      constructed_building = group.constructed_buildings_finished.select{|constructed_building| constructed_building.building_id == params[:building].to_i}.first
      unless constructed_building.nil?
        event_log = EventLog.new(
            constructed_building: constructed_building,
            event_id: params[:event].to_i,
            start: DateTime.now)
        event_log.save!
      end
    end
  end

  def set_vars
    @constructed_building = ConstructedBuilding.find(params[:constructed_building_id])
    @group = @constructed_building.group unless @constructed_building.nil?
  end

  def set_event_log
    @event_log = EventLog.find(params[:id])
  end

  def event_log_params
    params.require(:event_log).permit(:constructed_building_id, :event_id, :start, :end, :comment)
  end
end

app/views/event_logs/_form.html.erb
<%= form_with(model: event_log, url: group_constructed_building_event_log_path, local: true) do |form| %>
  <% if event_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_log.errors.count, "error") %> prohibited this event_log from being saved:</h2>

      <ul>
      <% event_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, id: :event_log_event_id %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start, id: :event_log_start %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :event_log_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_logs/edit.html.erb
<h1>Editing Event Log</h1>

<%= render 'form', event_log: @event_log %>

<%= icon_link_to 'search', 'Show', group_constructed_building_event_log_path(@group, @constructed_building, @event_log) %> |
<%= icon_link_to 'level-up', 'Back', group_constructed_building_event_logs_path %>

app/views/event_logs/index.html.erb
<h1>Event Logs</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Start</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_logs.each do |event_log| %>
      <tr>
        <td title="<%= event_log.event.comment %>"><%= event_log.event.name %></td>
        <td><%= event_log.start.localtime %></td>
        <td><%= event_log.comment %></td>
        <td><%= icon_link_to 'search', 'Show', group_constructed_building_event_log_path(@group, @constructed_building, event_log) %></td>
        <td><%= icon_link_to 'pencil', 'Edit', edit_group_constructed_building_event_log_path(@group, @constructed_building, event_log) %></td>
        <td><%= icon_link_to 'trash', 'Destroy', group_constructed_building_event_log_path(@group, @constructed_building, event_log), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Log', new_group_constructed_building_event_log_path %>

app/views/event_logs/new.html.erb
<h1>New Event Log</h1>

<%= render 'form', event_log: @event_log %>

<%= icon_link_to 'level-up', 'Back', edit_group_constructed_building_event_logs_path %>

app/views/event_logs/show.html.erb
<h1><%= @event_log.event.name %></h1>

<p>
  <strong>Event comment:</strong>
  <%= @event_log.event.comment %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event_log.start.localtime %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @event_log.comment %>
</p>

<%= icon_link_to 'pencil', 'Edit', edit_group_constructed_building_event_log_path(@group, @constructed_building, @event_log) %> |
<%= icon_link_to 'level-up', 'Back', group_constructed_building_event_logs_path %>