config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :accountings
  resources :tasks
  resources :categories
  resources :buildings
  resources :events
  resources :games
  resources :users
  resources :groups do
    resources :task_logs
    resources :constructed_buildings do
      resources :event_logs
    end
  end

  get '/add_event_log', to: 'event_logs#add'
  get '/add_task_log', to: 'task_logs#add'
  get '/start_task_log', to: 'task_logs#start'

  root to: 'groups#index'

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :game
  belongs_to :user
  has_many :constructed_buildings
  has_many :task_logs, -> { order(:id) }
  has_many :accountings

  validates :name, :presence => true
  validates :start_balance, :presence => true

  def balance
    self.start_balance +
        total_amount_of_constructed_buildings +
        total_amount_of_tasks +
        total_accountings
  end

  def points
    self.balance.to_f +
        self.constructed_buildings.inject(0){|sum, constructed_building| sum + constructed_building.building.cost}.to_f * 0.8 +
        self.population.to_f * 100
  end

  def population
    self.constructed_buildings
        .select { |constructed_building| constructed_building.under_construction == false }
        .inject(0){|sum, constructed_building| sum + constructed_building.building.inhabitants}
  end

  def constructable_buildings
    Building.all.order(:id).select{
      |building| self.constructed_buildings.none? {
          |constructed_building| constructed_building.building_id == building.id}
    }
  end

  def constructed_buildings_finished
    self.constructed_buildings.order(:id).select{|constructed_building| !constructed_building.under_construction}
  end

  def can_build?(cost)
    self.balance >= cost && !self.building_ban
  end

  private
  def total_amount_of_constructed_buildings
    total = 0
    self.constructed_buildings.each do |constructed_building|
      total += constructed_building.amount
    end
    total
  end

  def total_amount_of_tasks
    total = 0
    self.task_logs.each do |task_log|
      task = task_log.task
      if task.value > 0
        if task_log.done
          total = task.value
        end
      else
        if !task_log.done && (!task_log.on_time || game.is_over?)
          total = task.value
        end
      end
    end
    total
  end

  def total_accountings
    self.accountings.inject(0){|sum,e| sum + e.amount}
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_admin, only: [:new, :edit, :update, :destroy]
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_games, only: [:edit, :update, :new]

  # GET /groups
  def index
    if current_user.admin?
      @groups = Group.all.order(:id)
    else
      unless current_user.group.nil?
        redirect_to group_path(current_user.group)
      end
    end
    respond_to do |format|
      format.html
      format.json { render json: @groups, except: [:created_at, :updated_at], methods: [:balance, :points] }
    end
  end

  # GET /groups/1
  def show
    unless current_user.admin? || current_user.group.id == params[:id].to_i
      redirect_to groups_path
    end
    respond_to do |format|
      format.html
      format.json { render json: @group, only: :id, methods: [:balance, :points] }
    end
  end

  # GET /groups/new
  def new
    @group = Group.new @game
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      respond_to do |format|
        format.js { redirect_back fallback_location: @group, notice: 'Group was successfully updated.'}
        format.html { redirect_to @group, notice: 'Group was successfully updated.'}
      end
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private
  def set_group
    @group = Group.find(params[:id])
    @game = Game.find(@group.game_id) unless @group.nil?
    @buildings = Building.all
  end

  def set_games
    @games = Game.all
  end

  def group_params
    params.require(:group).permit(:game_id, :name, :email, :phone, :start_balance, :building_ban, :comment)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper

  def buildings_categories(buildings)
    buildings.collect {|building| building.category}.uniq
  end

  def constructed_buildings_categories(constructed_buildings)
    constructed_buildings.collect {|constructed_building| constructed_building.building.category}.uniq
  end

end

app/views/groups/_constructed_building.html.erb
<div class="col-12 col-md-6 col-lg-4">
  <div class="card">
    <div class="card-header <%= 'bg-secondary' if constructed_building.under_construction %>">
      <h4><%= link_to constructed_building.building.name, constructed_building.building %></h4>
      <div class="row">
        <div class="col-12 one-line">
          <%= icon 'dollar' %>
          <span class="number-format"><%= constructed_building.amount.to_i + constructed_building.building.cost.to_i %></span>
          <span class="float-right">
            <%= icon_link_to 'search', t(:show), constructed_building.building %>
            <% if constructed_building.under_construction || current_user.admin? %>
                <%= icon_link_to 'trash', t(:delete), group_constructed_building_path(@group, constructed_building), method: :delete, data: { confirm: t(:are_you_sure?) } %>
            <% end %>
          </span>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-6"><%= "#{ConstructedBuilding.human_attribute_name(:constructed_at)}" %></div>
        <div class="col-6"><%= icon 'clock-o' %><%= " #{format_time(constructed_building.construction_time.localtime)}" %></div>
        <% if constructed_building.under_construction %>
          <div class="col-6"><%= "#{ConstructedBuilding.human_attribute_name(:remaining_construction_time)}" %></div>
          <div class="col-6"><%= distance_of_time_in_words_to_now(Time.now - constructed_building.remaining_construction_time.seconds) %></div>
        <% end %>
        <div class="col-6"><%= "#{Building.human_attribute_name(:inhabitants)}" %></div>
        <div class="col-6"><%= icon 'users' %><%= " #{constructed_building.building.inhabitants}" %></div>
        <div class="col-6"><%= "#{Building.human_attribute_name(:required_building)}" %></div>
        <% unless constructed_building.building.required_building.nil? %>
          <div class="col-6"><%= icon 'building' %><%= " #{constructed_building.building.required_building.name}" %></div>
        <% else %>
          <div class="col-6"><%= icon 'building' %><%= " #{t(:nothing)}" %></div>
        <% end %>
      </div>
    </div>
    <div class="card-footer">
      <% constructed_building.event_logs.each do |event_log| %>
        <div class="row">
          <div class="col-12">
            <%= "#{event_log.event.name} #{t(:at)} #{format_date_time(event_log.start.localtime)}" %>
          </div>
          <div class="col-12">
            <% if event_log.remaining_time > 0 %>
              <%= t(:remaining) %>
              <%= icon 'bomb', title: Event.human_attribute_name(:impact_percent) %>
              <span class="number-format"><%= "#{event_log.remaining_impact}" %></span><%="% / "%>
              <%= icon 'clock-o', title: Event.human_attribute_name(:duration) %>
              <%=" #{distance_of_time_in_words_to_now(Time.now - event_log.remaining_time)}" %>
            <% else %>
              <%= "#{t(:ended)} #{t(:at)} #{format_date_time(event_log.end.localtime)}" %>
            <% end %>
          </div>
          <div class="col-12">
            <%= t(:demage) %>
            <%= icon 'bomb', title: Event.human_attribute_name(:impact_percent) %>
            <%= "#{event_log.event.impact_percent}% / " %>
            <%= icon 'clock-o', title: Event.human_attribute_name(:duration) %>
            <%=" #{event_log.event.duration_min} #{t(:minutes)}" %>
          </div>
          <hr>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.select :game_id, @games.collect {|game| [game.name, game.id]}, blank: " " %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :group_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :group_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :group_phone %>
  </div>

  <div class="field">
    <%= form.label :start_balance %>
    <%= form.text_field :start_balance, id: :group_start_balance %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :group_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="col-12">
  <div class="card">
    <div class="card-header bg-<%= group.building_ban ? 'danger' : 'light'%>">
      <span class="badge badge-info badge-pill float-right" title="<%= "#{group.game.start.localtime} - #{group.game.end.localtime}" %>">
        <%= group.game %>
      </span>
      <h4><%= group.name %></h4>
      <span class="badge badge-<%= group.building_ban ? 'danger' : 'info'%> badge-pill" title="<%= "#{group.game.start.localtime} - #{group.game.end.localtime}" %>">
        <%= "#{Group.human_attribute_name(:bauilding_ban)}: " %>
        <%= check_box_tag "building-ban-#{group.id}", group.building_ban, group.building_ban %>
      </span>
      <span class="float-right">
        <%= icon_link_to 'search', t(:show), group %>
        <%= icon_link_to 'pencil', t(:edit), edit_group_path(group) %>
        <%= icon_link_to 'trash', t(:delete), group, method: :delete, data: { confirm: t(:are_you_sure?) } %>
      </span>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-6"><%= "#{Group.human_attribute_name(:email)}: #{group.email}" %></div>
        <div class="col-6"><%= "#{Group.human_attribute_name(:balance)}: " %><%= icon 'dollar' %><span class="number-format"><%= group.balance %></span></div>
        <div class="col-6"><%= "#{Group.human_attribute_name(:phone)}: #{group.phone}" %></div>
        <div class="col-6"><%= "#{Group.human_attribute_name(:population)}: " %><span class="number-format"><%= group.population %></div>
        <div class="col-6"></div>
        <div class="col-6"><%= "#{Group.human_attribute_name(:points)}: " %><span class="number-format"><%= group.points %></div>
        <div class="col-12"><%= group.comment %></div>
      </div>
    </div>
    <div class="card-footer">
      <h6><%= t('group.constructed_buildings') %></h6>
      <div class="row">
        <% if group.constructed_buildings.length > 0 %>
          <% group.constructed_buildings.each do |constructed_building| %>
            <div class="col-6 col-sm-4 col-md-3"><%= constructed_building.building.name %></div>
          <% end %>
        <% else %>
          <div class="col-12"><%= t('group.no_buildings_constructed_now') %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    $('<%= "#building-ban-#{group.id}" %>').bind('change', function(){
        $.ajax({
            url: '<%= group_path(group.id) %>',
            type: 'PUT',
            data: {'group': {'building_ban': this.checked}}
        })
    })
</script>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= icon_link_to 'search', 'Show', group_path(@group) %> |
<%= icon_link_to 'level-up', 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="row">
  <div class="col-8">
    <% if current_user.admin? %>
      <h1><%= Group.model_name.human(count: 2) %></h1>
    <% else %>
      <h1><%= Group.model_name.human   %></h1>
    <% end %>
  </div>
  <% if current_user.admin? %>
    <div class="col-4">
      <h6 class="float-right action-buttons">
        <%= icon_link_to 'plus', t(:new), new_group_path %>
      </h6>
    </div>
  <% end %>
</div>


<% if @groups.nil? %>
  <div class="row">
    <div class="col-12">
      <%= t(:no_group) %>
    </div>
  </div>
<% else %>
  <div class="row">
    <% @groups.each do |group| %>
      <%= render group %>
    <% end %>
  </div>
<% end %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= icon_link_to 'level-up', 'Back', groups_path %>

app/views/groups/show.html.erb
<div class="row">
  <div class="col-8 col-md-9">
    <div class="row">
      <div class="col-12 col-md-5"><h1 name="group_title" id="<%= @group.id %>"><%= @group.name %></h1></div>
      <div class="col-12 col-sm-6 col-md-4 one-line"><h2 id="group_balance">
        <%= icon 'dollar' %><span class="number-format"><%= @group.balance %></span>
      </h2></div>
      <div class="col-12 col-sm-6 col-md-3 one-line"><h2 id="group_balance">
        <%= icon 'users' %><span class="number-format"><%= @group.population %></span>
      </h2></div>
    </div>
  </div>
  <div class="col-4 col-md-3">
    <h6 class="float-right action-buttons">
      <%= icon('info-circle fa-2x', title: "#{@group.email} | #{@group.phone}", 'data-toggle' => 'modal', 'data-target' => '#infoModal') %>
      <%= icon_link_to 'pencil', t(:edit), edit_group_path(@group) %>
      <%= icon_link_to 'level-up', t(:back), groups_path %>
    </h6>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <span class="badge badge-info badge-pill float-right"
          title="<%= "#{format_date_time(@group.game.start.localtime)} - #{format_date_time(@group.game.end.localtime)}" %>">
      <%= @group.game %>
    </span>
  </div>
</div>

<% if @group.building_ban %>
  <div class="building_ban_banner">
    <h5>Das Bauen von Gebäuden ist momentan nicht möglich. Dies wurde von der Spielleitung verordnet.</h5>
  </div>
<% end %>

<% @group.accountings.each do |accounting|%>
  <% unless accounting.hide %>
    <div class="card" id="card-id-<%= accounting.id %>">
      <div class="card-body">
        <div class="float-right">
          <%= button_to "X", accounting_path(accounting), params: {accounting: {hide: true}}, method: :put, remote: true %>
        </div>
        <span class="number-format"><%= accounting.amount %></span><%=".- #{accounting.comment}" %>
      </div>
    </div>
  <% end %>
<% end %>

<ul class="nav nav-tabs" id="groupTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="constructed-tab" data-toggle="tab" href="#constructed" role="tab" aria-controls="constructed" aria-selected="true">
      <%= t('group.constructed_buildings') %>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="not-constructed-tab" data-toggle="tab" href="#not-constructed" role="tab" aria-controls="not-constructed" aria-selected="false">
      <%= t('group.not_constructed_buildings') %>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="tasks-tab" data-toggle="tab" href="#tasks" role="tab" aria-controls="tasks" aria-selected="false">
      <%= t('group.tasks') %>
    </a>
  </li>
</ul>
<div class="tab-content" id="groupTabContent">
  <div class="tab-pane fade show active" id="constructed" role="tabpanel" aria-labelledby="constructed-tab">
    <% constructed_buildings_categories(@group.constructed_buildings).each do |category| %>
      <div class="row">
        <div class="col-12">
          <div class="card card-border-less">
            <div class="card-header" style="background-color: <%= category.color %>; color: #ffffff">
              <h4 class="card-title"><%= category.name %></h4>
            </div>
            <div class="card-body">
              <div class="row">
                <% @group.constructed_buildings.select{|cb| cb.building.category.eql?(category)}.each do |constructed_building| %>
                    <%= render partial: 'constructed_building', locals: {constructed_building: constructed_building} %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="tab-pane fade" id="not-constructed" role="tabpanel" aria-labelledby="not-constructed-tab">
    <% buildings_categories(@group.constructable_buildings).each do |category| %>
      <div class="row">
        <div class="col-12">
          <div class="card card-border-less">
            <div class="card-header" style="background-color: <%= category.color %>; color: #ffffff">
              <h4 class="card-title"><%= category.name %></h4>
            </div>
            <div class="card-body">
              <div class="row">
                <% @group.constructable_buildings.select{|building| building.category.eql?(category)}.each do |building| %>
                  <%= render partial: 'buildings/building_list_item', locals: {building: building, group: @group} %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="tab-pane fade" id="tasks" role="tabpanel" aria-labelledby="tasks-tab">
    <div class="row">
      <% @group.task_logs.each do |task_log| %>
        <%= render partial: 'task_logs/task_log', locals: {task_log: task_log} %>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="infoModalLabel"><%= @group.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <%= "#{Group.human_attribute_name(:email)} : #{@group.email}" %>
        </div>
        <div>
          <%= "#{Group.human_attribute_name(:phone)} : #{@group.phone}" %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'groups/show' %>