config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :accountings
  resources :tasks
  resources :categories
  resources :buildings
  resources :events
  resources :games
  resources :users
  resources :groups do
    resources :task_logs
    resources :constructed_buildings do
      resources :event_logs
    end
  end

  get '/add_event_log', to: 'event_logs#add'
  get '/add_task_log', to: 'task_logs#add'
  get '/start_task_log', to: 'task_logs#start'

  root to: 'groups#index'

end

app/models/task_log.rb
class TaskLog < ApplicationRecord
  belongs_to :task

  def started
    !self.start.nil?
  end

  def on_time
    if started
      self.start.getutc + self.task.duration_min * 60 > Time.now.getutc
    else
      true
    end
  end

  def remaining_time
    remaining_time = self.task.duration_min
    if self.started
      remaining_time = (self.start.getutc + self.task.duration_min * 60) - DateTime.now.getutc
    end
    remaining_time > 0 ? remaining_time : 0
  end

  def current_amount
    amount = 0
    task = self.task
    if task.value > 0
      if self.done
        amount = task.value
      end
    else
      if !self.done && (!self.on_time || self.game.is_over?)
        amount = task.value
      end
    end
    amount
  end

end

app/controllers/task_logs_controller.rb
class TaskLogsController < ApplicationController
  before_action :set_task_log, only: [:show, :edit, :update, :destroy]

  # GET /task_logs
  def index
    @task_logs = TaskLog.all.order(:id)
  end

  # GET /task_logs/1
  def show
  end

  # GET /task_logs/new
  def new
    @task_log = TaskLog.new
  end

  # GET /task_logs/1/edit
  def edit
  end

  def add
    if params[:group] == 'all'
      game = Game.find(params[:game])
      game.groups.each do |group|
        create_task_log(params, group.id)
      end
    else
      create_task_log(params, params[:group])
    end
    redirect_to game_path(params[:game])
  end

  # POST /task_logs
  def create
    @task_log = TaskLog.new(task_log_params)

    if @task_log.save
      redirect_to @task_log, notice: 'Task log was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /task_logs/1
  def update
    unless params[:task_log].nil? && params[:task_log][:done].nil?
      set_end_to_now
    end
    @task_log.update(task_log_params)
  end

  # DELETE /task_logs/1
  def destroy
    @task_log.destroy
    redirect_back fallback_location: root_path, notice: 'Task log was successfully destroyed.'
  end

  def start
    task_log = TaskLog.find(params[:task_log_id])
    if task_log.start.nil?
      task_log.start = DateTime.now
      task_log.save!
      redirect_back fallback_location: root_path, notice: 'Task log was successfully started.'
    else
      redirect_back fallback_location: root_path, alert: 'Task log was already started.'
    end

  end

  private
  def create_task_log(params, group_id)
    task_log = TaskLog.new(
        task: Task.find(params[:task]),
        group_id: group_id,
        start: nil,
        comment: '',
        done: false
    )
    task_log.save
  end

  def set_task_log
    @task_log = TaskLog.find(params[:id])
  end

  def task_log_params
    params.require(:task_log).permit(:task_id, :group_id, :start, :end, :comment, :done)
  end

  def set_end_to_now
    if params[:task_log][:done] == 'true'
      params[:task_log][:end] = DateTime.now
    else
      params[:task_log][:end] = nil
    end
  end
end

app/views/task_logs/_form.html.erb
<%= form_with(model: task_log, local: true) do |form| %>
  <% if task_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_log.errors.count, "error") %> prohibited this task_log from being saved:</h2>

      <ul>
      <% task_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.number_field :task_id, id: :task_log_task_id %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.number_field :group_id, id: :task_log_group_id %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start, id: :task_log_start %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :task_log_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_logs/_task_log.html.erb
<div class="col-12 col-sm-6 col-md-4">
  <div class="card">
    <div class="card-header">
      <div class="float-right">
        <% if current_user.admin? %>
          <%= check_box_tag "task-log-#{task_log.id}", task_log.done, task_log.done, :class => 'task_log_checkbox' %>
        <% elsif task_log.done %>
          <span class="badge badge-success badge-pill float-right" %>
            <%= icon 'check' %>
            <%= "#{t('task_log.done')}" %>
          </span>
        <% else %>
          <span class="badge badge-danger badge-pill float-right" %>
            <%= icon 'close' %>
            <%= "#{t('task_log.open')}" %>
          </span>
        <% end %>
        <br/>
        <% if task_log.task.optional %>
          <span class="badge badge-success badge-pill float-right" title="<%= "#{Task.human_attribute_name(:optional)}" %>">
            <%= "#{Task.human_attribute_name(:optional)}" %>
          </span>
        <% else %>
          <span class="badge badge-danger badge-pill float-right" title="<%= "#{Task.human_attribute_name(:optional)}" %>">
            <%= "#{Task.human_attribute_name(:obligation)}" %>
          </span>
        <% end %>
      </div>
      <h4><%= task_log.task.name %></h4>
      <div class="row">
        <div class="col-4">
          <%= icon 'dollar', title: "#{Event.human_attribute_name(:impact)}" %>
          <span class="number-format"><%= task_log.task.value %></span>
        </div>
        <div class="col-8">
          <%= icon 'clock-o', title: "#{Event.human_attribute_name(:duration)}" %>
          <%= "#{task_log.task.duration_min} #{t(:minutes)}" %>
          <% if current_user.admin? %>
            <span class="float-right">
              <%= icon_link_to 'trash', t(:delete), group_task_log_path(@group, task_log), method: :delete, data: {confirm: t(:are_you_sure?)} %>
            </span>
          <% end %>
        </div>
      </div>
    </div>

    <div class="card-body">
      <div class="row">
        <div class="col-12">
          <% if task_log.started %>
            <%= task_log.task.description %>
          <% else %>
            <form action="<%= start_task_log_path %>" method="get">
              <input name="task_log_id" value="<%= task_log.id %>" hidden>
              <button type="submit" class="btn btn-default btn-sm pull-right">
                <%= t(:start_task) %>
              </button>
            </form>
          <% end %>
        </div>
      </div>
    </div>
    <% if task_log.started %>
    <div class="card-footer">
      <% if task_log.on_time %>
        <strong><%= t(:remaining) %>:</strong>
        <%= " #{distance_of_time_in_words_to_now(Time.now - task_log.remaining_time.seconds)}" %>
      <% else %>
        <strong><%= t(:time_is_up) %>.</strong>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

<script>
  $('<%= "#task-log-#{task_log.id}" %>').bind('change', function(){
      $.ajax({
          url: '<%= group_task_log_path(task_log.group_id, task_log) %>',
          type: 'PUT',
          data: {'task_log': {'done': this.checked}}
      })
  })
</script>

app/views/task_logs/edit.html.erb
<h1>Editing Task Log</h1>

<%= render 'form', task_log: @task_log %>

<%= link_to 'Show', @task_log %> |
<%= link_to 'Back', task_logs_path %>

app/views/task_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Logs</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Group</th>
      <th>Start</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_logs.each do |task_log| %>
      <tr>
        <td><%= task_log.task_id %></td>
        <td><%= task_log.group_id %></td>
        <td><%= task_log.start.localtime %></td>
        <td><%= task_log.comment %></td>
        <td><%= link_to 'Show', task_log %></td>
        <td><%= link_to 'Edit', edit_task_log_path(task_log) %></td>
        <td><%= link_to 'Destroy', task_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Log', new_task_log_path %>

app/views/task_logs/new.html.erb
<h1>New Task Log</h1>

<%= render 'form', task_log: @task_log %>

<%= link_to 'Back', task_logs_path %>

app/views/task_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @task_log.task_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @task_log.group_id %>
</p>

<p>
  <strong>Start:</strong>
  <%= @task_log.start.localtime %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @task_log.comment %>
</p>